#!/bin/bash

echo "🔍 Checking Claude Executor logs..."
echo ""
echo "Run this command to see what's happening:"
echo ""
echo "fly logs -a uncle-frank-claude | tail -50"
echo ""
echo "Look for:"
echo "- 'which claude' output"
echo "- 'Claude Code not available' messages"
echo "- Error messages about command execution"
echo ""
echo "If you see 'Claude Code not available', it means:"
echo "1. Claude Code CLI is not installed in the container"
echo "2. Or it's not in the PATH"
echo ""
echo "To SSH into the container and check:"
echo "fly ssh console -a uncle-frank-claude"
echo "which claude"
echo "claude --version"