#!/bin/bash

echo "📋 Instructions to check Fly.io logs:"
echo "===================================="
echo ""
echo "1. Check recent logs:"
echo "   fly logs -a uncle-frank-claude | tail -100"
echo ""
echo "2. Check for Claude detection:"
echo "   fly logs -a uncle-frank-claude | grep -i 'which claude'"
echo ""
echo "3. Check for errors:"
echo "   fly logs -a uncle-frank-claude | grep -i error"
echo ""
echo "4. SSH into container to debug:"
echo "   fly ssh console -a uncle-frank-claude"
echo "   Then run:"
echo "   - which claude"
echo "   - claude --version"
echo "   - claude auth status"
echo "   - echo 'test' | claude --dangerously-skip-permissions chat"
echo ""
echo "5. Check if setup script ran:"
echo "   fly logs -a uncle-frank-claude | grep -i 'claude code cli'"