#!/bin/bash

# DEPLOY GITHUB-INTEGRATED CLAUDE - RUN THIS NOW!

echo "🚀 Deploying GitHub-Integrated Claude Executor"
echo "============================================"
echo ""
echo "IMPORTANT: You need to set your GitHub token first!"
echo ""
echo "Run these commands:"
echo ""
echo "# 1. Set your GitHub token from Vercel (replace with your actual token):"
echo "export GITHUB_TOKEN='your-github-token-here'"
echo ""
echo "# 2. Update Fly.io to use GitHub-integrated version:"
echo "cp Dockerfile.github Dockerfile"
echo "cp server-github-integrated.js server.js"
echo ""
echo "# 3. Set GitHub secrets on Fly.io:"
echo "fly secrets set GITHUB_TOKEN=\"\$GITHUB_TOKEN\" -a uncle-frank-claude"
echo "fly secrets set GITHUB_REPO=\"bhuman-ai/unclefrank-bootstrap\" -a uncle-frank-claude"
echo "fly secrets set GITHUB_USER=\"bhuman-ai\" -a uncle-frank-claude"
echo "fly secrets set GITHUB_EMAIL=\"frank@unclefrank.ai\" -a uncle-frank-claude"
echo ""
echo "# 4. Deploy to Fly.io:"
echo "fly deploy --strategy rolling"
echo ""
echo "# 5. Test it:"
echo "curl -X POST https://uncle-frank-claude.fly.dev/api/sessions -H 'Content-Type: application/json' -d '{}'"
echo ""
echo "This will:"
echo "- Clone your repository"
echo "- Create a new branch"
echo "- Give Claude actual file system access"
echo "- Enable real file creation and git operations"