#!/bin/bash

echo "🔧 Claude Code CLI Fix Instructions"
echo "================================="
echo ""
echo "The issue: Claude Code CLI is not properly installed or authenticated in the container."
echo ""
echo "Step 1: SSH into the Fly.io container"
echo "--------------------------------------"
echo "Run: fly ssh console -a uncle-frank-claude"
echo ""
echo "Step 2: Check if Claude Code CLI is installed"
echo "---------------------------------------------"
echo "Once in the container, run:"
echo "  which claude"
echo "  claude --version"
echo ""
echo "Step 3: If not installed, install it"
echo "------------------------------------"
echo "  npm install -g @anthropic-ai/claude-code"
echo ""
echo "Step 4: Authenticate Claude Code CLI"
echo "------------------------------------"
echo "  claude login"
echo ""
echo "This will open a browser window for authentication."
echo "Complete the authentication process."
echo ""
echo "Step 5: Test Claude Code CLI"
echo "----------------------------"
echo "  echo 'Create a test file' | claude chat"
echo ""
echo "Step 6: Exit and restart the container"
echo "--------------------------------------"
echo "  exit"
echo "  fly apps restart uncle-frank-claude"
echo ""
echo "Alternative: Update Dockerfile to use API instead"
echo "------------------------------------------------"
echo "If Claude Code CLI authentication doesn't persist,"
echo "we need to modify the approach to use the Anthropic API"
echo "with proper file creation capabilities."