#!/bin/bash
# Script to help set up Claude manual session

echo "Setting up Claude manual session..."
echo ""
echo "I'll now start the Claude authentication process."
echo "Follow these steps:"
echo ""
echo "1. Run this command in your local terminal:"
echo "   ~/.fly/bin/fly ssh console --app uncle-frank-claude"
echo ""
echo "2. Once connected, run:"
echo "   tmux -f /etc/tmux.conf attach -t claude-manual"
echo ""
echo "3. In the tmux session, run:"
echo "   claude --dangerously-skip-permissions"
echo ""
echo "4. Claude will show a URL. To copy it:"
echo "   - Press Ctrl+b then ["
echo "   - Use arrow keys to navigate to the URL"
echo "   - Press Space to start selection"
echo "   - Move to select the full URL"
echo "   - Press Enter to copy"
echo "   - Press q to exit copy mode"
echo ""
echo "5. Open the URL in your browser and get the auth code"
echo ""
echo "6. Back in tmux, paste the auth code and press Enter"
echo ""
echo "7. When asked for theme, press 1 for dark theme"
echo ""
echo "8. Once authenticated, detach from tmux with Ctrl+b then d"
echo ""
echo "9. Exit the SSH session with 'exit'"
echo ""
echo "The Claude session will persist across deployments!"