#!/bin/bash

# Simple Claude Code Authentication for Fly.io

echo "🔧 Simple Claude Code Authentication"
echo "===================================="
echo ""
echo "Since port forwarding isn't working, let's try direct methods:"
echo ""
echo "Method 1: Direct SSH with Environment Variables"
echo "----------------------------------------------"
echo "fly ssh console -a uncle-frank-claude"
echo ""
echo "Once connected, run:"
echo "export CLAUDE_HEADLESS=true"
echo "export NO_BROWSER=1"
echo "claude login --no-browser 2>&1 | grep -E '(http|https)://'"
echo ""
echo "This should print JUST the auth URL without hanging."
echo ""
echo "Method 2: Use Fly.io's Built-in Proxy"
echo "-------------------------------------"
echo "Try this instead of port forwarding:"
echo "fly ssh console -a uncle-frank-claude -L 8080:localhost:8080"
echo ""
echo "Method 3: Check if Already Authenticated"
echo "----------------------------------------"
echo "Sometimes Claude is already authenticated. Check with:"
echo "fly ssh console -a uncle-frank-claude"
echo "claude doctor"
echo "claude chat --message 'test'"
echo ""
echo "Method 4: Use the API Instead"
echo "-----------------------------"
echo "If Claude Code auth is too complex on a server,"
echo "we already have API support built in!"
echo ""
echo "Just run:"
echo "fly secrets set ANTHROPIC_API_KEY='your-key' -a uncle-frank-claude"
echo ""
echo "Get a key from: https://console.anthropic.com/settings/keys"